### ISSUE TITLE
[Phase 3] MedicineQuery.java 약 재고 조회&수량변경 오류

### ISSUE THREAD

**Issue by yerim10044001** [eugene131/DB_TeamP#11]
약사 로그인 시 사용할 수 있는 메뉴 중 3. 약 재고 조회 기능에서
추가하고자 하는 약의 재고가 없을 때 약을 추가하려고 하니 오류가 발생합니다.

![image](https://user-images.githubusercontent.com/86493874/202895245-8476c8fc-074a-4df9-8cad-ed1781c77a00.png)

새로운 약을 추가할 때에는 m_insert()함수를 사용하는데 이때 받아오는 p_num값이 ""(빈 문자열) 이기 때문에 오류가 발생하였습니다.

기존 코드에서는 약 재고조회를 했을 때 약국번호(p_num)을 함께 조회하기 때문에 조회하고자 하는 약 재고가 없다면 ""값이 들어가게 됩니다.
medicine_stock() 함수를 호출했을 때 받은 client_ID로 약국번호(p_num)을 먼저 조회한 후, 함수에 사용하여야 합니다. 
![image](https://user-images.githubusercontent.com/86493874/202895348-2c06d60c-9b39-43c3-8cd5-1b3adff7db9b.png)

**Comment by eugene131** [comment]
p_num을 받는 pharmarcy_num 메서드를 추가해서 p_num을 따로 받도록 설계했습니다!
