### ISSUE TITLE
[phase4] 12/2 수정목록

### ISSUE THREAD

**Issue by yerim10044001** [eugene131/DB_TeamP#17]
- [x] css 완성하기
- [x] 최종발표 ppt 내용준비, 내용 구성
- [x] 고객정보 수정기능 수정
- [x] m_insert.html, m_insert_res.jsp 수정
- [x] 데모영상 제작

**Comment by eugene131** [comment]
하나 깜빡했는데 저희 데모 영상도 만들어야 합니다!

**Comment by yerim10044001** [comment]
수정목록에 데모영상도 추가하였습니다!
